---
sudo: required
language: python

branches:
  only:
    - master

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule docker

script:
  - molecule test

notifications:
  email:
    recipients:
      - avuong@cachemeoutside.io
    on_success: change
    on_failure: change
