---
roles:
  - name: "uclalib_role_apache"
    src: "git+https://github.com/UCLALibrary/uclalib_role_apache.git"
  - name: "uclalib_role_postgresql"
    src: "git+https://github.com/UCLALibrary/uclalib_role_postgresql.git"
