---
roles:
  - "git+https://github.com/UCLALibrary/uclalib_role_rhelscl.git" 
  - "git+https://github.com/UCLALibrary/uclalib_role_apache.git" 
  - "git+https://github.com/UCLALibrary/uclalib_role_postgresql.git"
