---

- name: Install Zabbix Server packages
  # noqa: package-latest
  yum:
    name: "{{ zabbix_server_pkgs }}"
    state: latest

- name: Upload Zabbix Server Configuration
  template:
    src: zabbix-server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    mode: '0640'
  notify: Restart Zabbix Server

- name: Enable Zabbix Server on boot
  service:
    name: zabbix-server
    enabled: true
  notify: Start Zabbix Server

- name: Configure Zabbix user to run nmap in privileged mode
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "zabbix ALL=(ALL) NOPASSWD: /usr/bin/nmap"
    validate: "/usr/sbin/visudo -cf %s"
