---

- name: Enable Zabbix Frontend Repo
  ini_file:
    dest: /etc/yum.repos.d/zabbix.repo
    section: zabbix
    owner: root
    group: root
    mode: "0644"
    option: enabled
    value: "1"
    no_extra_spaces: true

- name: Enable php stream
  command:
    cmd: dnf module --assumeyes switch-to {{ zabbix_php_stream }}
    warn: false
  changed_when: "'Nothing to do' not in stream_switch.stdout"
  when: zabbix_php_stream is defined
  register: stream_switch

- name: Install Zabbix Frontend packages
  # noqa: package-latest
  yum:
    name: "{{ zabbix_frontend_pkgs }}"
    state: latest

- name: Configure Timezone for Zabbix
  lineinfile:
    path: '/etc/php-fpm.d/zabbix.conf'
    line: 'php_value[date.timezone] = America/Los_Angeles'
  notify: Restart PHP FPM

- name: Enable PHP FPM service
  service:
    name: php-fpm
    enabled: true
  notify: Start PHP FPM

- name: Delete sample Zabbix HTTPD conf
  file:
    path: /etc/httpd/conf.d/zabbix.conf
    state: absent
  notify: Restart HTTPD

- name: Ensure SSL path created
  file:
    path: "{{ item.value.ssl_path }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: >-
    zabbix_vhost_config is defined and
    item.value.use_https and
    not item.value.use_acme
  with_dict: "{{ zabbix_vhost_config }}"

- name: Upload SSL certificate
  copy:
    src: "{{ item.value.ssl_src_path }}/cert.pem"
    dest: "{{ item.value.ssl_path }}/cert.pem"
    owner: root
    group: root
    mode: '0644'
  when: >-
    zabbix_vhost_config is defined and
    item.value.use_https and
    not item.value.use_acme
  with_dict: "{{ zabbix_vhost_config }}"

- name: Upload SSL chain
  copy:
    src: "{{ item.value.ssl_src_path }}/chain.pem"
    dest: "{{ item.value.ssl_path }}/chain.pem"
    owner: root
    group: root
    mode: '0644'
  when: >-
    zabbix_vhost_config is defined and
    item.value.use_https and
    not item.value.use_acme
  with_dict: "{{ zabbix_vhost_config }}"

- name: Upload SSL key
  copy:
    src: "{{ item.value.ssl_src_path }}/privkey.pem"
    dest: "{{ item.value.ssl_path }}/privkey.pem"
    owner: root
    group: root
    mode: '0600'
  when: >-
    zabbix_vhost_config is defined and
    item.value.use_https and
    not item.value.use_acme
  with_dict: "{{ zabbix_vhost_config }}"

- name: Create Zabbix VHost
  template:
    src: zabbix-httpd.conf.j2
    dest: /etc/httpd/vhosts.d/zabbix.conf
    owner: root
    group: root
    mode: '0644'
  with_dict: "{{ zabbix_vhost_config }}"
  notify: Restart HTTPD

- name: Create Frontend Config for Zabbix
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: apache
    group: apache
    mode: '0640'
  notify: Restart HTTPD
