---

- name: Install Zabbix Agent packages
  # noqa: package-latest
  yum:
    name: "{{ zabbix_agent_pkgs }}"
    state: latest

- name: Create TLS directory if setting up agent encryption
  file:
    path: "{{ zabbix_agent_tls_psk_directory }}"
    owner: zabbix
    group: root
    mode: '0750'
    state: directory
  when: zabbix_agent_encrypt

- name: Upload PSK file if PSK encryption is flagged
  copy:
    content: "{{ zabbix_agent_tls_psk }}"
    dest: "{{ zabbix_agent_tls_psk_directory }}//zabbix-agent-tls-psk"
    owner: zabbix
    group: root
    mode: '0640'
  when: zabbix_agent_encrypt and zabbix_agent_tls_type == "psk"

- name: Enable Zabbix Agent on boot
  service:
    name: zabbix-agent
    enabled: true
  notify: Start Zabbix Agent

- name: Create Zabbix Agent extra config directory
  file:
    path: "{{ zabbix_agent_extra_config_path }}"
    owner: zabbix
    group: zabbix
    mode: '0750'
    state: directory

- name: Put Zabbix Agent config in place
  template:
    src: zabbix-agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Zabbix Agent
  tags:
    - agent-config-file

- name: Put in place Zabbix Agent Helper Scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - check_network_shares
  tags:
    - agent-helper-scripts

- name: Put in place Zabbix Agent extra config file
  template:
    src: "zabbix-extra.conf.j2"
    dest: "{{ zabbix_agent_extra_config_path }}/extra-params.conf"
    owner: zabbix
    group: zabbix
    mode: '0640'
  when: zabbix_agent_extra_config | length > 0
  notify: Restart Zabbix Agent
  tags:
    - agent-extra-configs
