---

- include_tasks: setup-vars.yml

- include_tasks: install-repo.yml

- include_tasks: install-agent.yml

- include_tasks: install-server.yml
  when: zabbix_install_server

- include_tasks: install-server-web.yml
  when: zabbix_install_server

- include_tasks: init-db.yml
  when: zabbix_install_server
