---

- include_tasks: setup-vars.yml
  tags: [ agent, server ]

- include_tasks: install-repo.yml
  tags: [ agent, server ]

- include_tasks: install-agent.yml
  tags: [ agent, server ]

- include_tasks: install-server.yml
  tags: [ server ]

- include_tasks: install-server-web.yml
  tags: [ server ]

- include_tasks: init-db.yml
  tags: [ server ]
