---

- import_tasks: setup-vars.yml

- import_tasks: install-repo.yml

- import_tasks: install-agent.yml

- import_tasks: install-server.yml
  when: zabbix_install_server

- import_tasks: install-server-web.yml
  when: zabbix_install_server

- import_tasks: init-db.yml
  when: zabbix_install_server
