---

- name: Include Specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
