---

- name: Start Zabbix Server
  service:
    name: zabbix-server
    state: started

- name: Start Zabbix Agent
  service:
    name: zabbix-agent
    state: started

- name: Start PHP FPM
  service:
    name: "{{ (ansible_distribution_major_version == '7') | ternary('rh-php72-php-fpm', 'php-fpm') }}"
    state: started

- name: Start HTTPD
  service:
    name: httpd
    state: started

- name: Restart Zabbix Server
  service:
    name: zabbix-server
    state: restarted

- name: Restart Zabbix Agent
  service:
    name: zabbix-agent
    state: restarted

- name: Restart PHP FPM
  service:
    name: "{{ (ansible_distribution_major_version == '7') | ternary('rh-php72-php-fpm', 'php-fpm') }}"
    state: restarted

- name: Restart HTTPD
  service:
    name: httpd
    state: restarted
